[versions]
kotlin = "2.0.20"
shadow = "8.3.3"
paper-api = "1.21.10-R0.1-SNAPSHOT"
paperweight = "2.0.0-beta.19"
minotaur = "2.8.7"
sonatype-central-portal-publisher = "1.2.4"

[libraries]
kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }

[plugins]
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
sonatype-central-portal-publisher = { id = "net.thebugmc.gradle.sonatype-central-portal-publisher", version.ref = "sonatype-central-portal-publisher" }